# UI Colors (extended) — dos-moos (A-custom · Muted Sage)
accent = "#819890"
cursor = "#F4E276"

# Primary colors
foreground = "#F8EBE3"
background = "#131516"

# Selection colors
selection_foreground = "#131516"
selection_background = "#A5B5AB"

# Normal colors (ANSI 0-7)
color0 = "#131516"
color1 = "#F0334A"
color2 = "#819890"
color3 = "#F4E276"
color4 = "#A5B5AB"
color5 = "#72856C"
color6 = "#819890"
color7 = "#A5B5AB"

# Bright colors (ANSI 8-15)
color8 = "#3A4849"
color9 = "#F0334A"
color10 = "#A5B5AB"
color11 = "#F4E276"
color12 = "#A5B5AB"
color13 = "#819890"
color14 = "#A5B5AB"
color15 = "#F8EBE3"
