-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    border_size = 1,
    col = {
      active_border = "rgb(A5B5AB)",
      inactive_border = "rgb(35373A)",
    },
  },
  group = {
    col = {
      border_active = "rgb(A5B5AB)",
      border_inactive = "rgb(35373A)",
    },
  },
  decoration = {
    rounding = 4,
    rounding_power = 2,
    active_opacity = 0.94,
    inactive_opacity = 0.94,
    fullscreen_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 15,
      render_power = 3,
      color = "rgba(0A0B06ee)",
      color_inactive = "rgba(0A0B0688)",
    },
    blur = {
      enabled = false,
    },
  },
})

hl.window_rule({
  opacity = "1.0 override 1.0 override",
  match = {
    class = "^(imv|mpv|vlc|org.gnome.NautilusPreviewer|org.gnome.Evince|com.gabm.satty|zoom|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta)$",
  },
})
